name: macOS Build

on:
  workflow_dispatch:


env:
  BUILD_TYPE: Release
  LDFLAGS: "-L/usr/local/opt/llvm/lib"
  CPPFLAGS: "-I/usr/local/opt/llvm/include"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install LLVM and Cmake
        run: brew install llvm cmake
      - name: set PATH
        run: echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Make Tests
        working-directory: ${{github.workspace}}/tests
        run: make all

      - name: Get output obfuscated
        working-directory: ${{github.workspace}}/tests
        run: ./obfuscatedbinary 2 3 >>obsr

      - name: Get output original
        working-directory: ${{github.workspace}}/tests
        run: ./originalbinary 2 3 >>origr

      - name: Check similarity
        working-directory: ${{github.workspace}}/tests
        run: cmp -s obsr origr
