name: Ubuntu Build

on:
  workflow_dispatch:


env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install prereq
        run: sudo apt install lsb-release wget software-properties-common gnupg cmake ninja-build
        
      - name: install llvm
        run: wget https://apt.llvm.org/llvm.sh; chmod +x llvm.sh; sudo ./llvm.sh 17 all

      - name: Adding LLVM bin dir to PATH
        run: llvm-config-17 --bindir >> $GITHUB_PATH

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Make Tests
        working-directory: ${{github.workspace}}/tests
        run: make all

      - name: Get output obfuscated
        working-directory: ${{github.workspace}}/tests
        run: ./obfuscatedbinary 2 3 >>obsr

      - name: Get output original
        working-directory: ${{github.workspace}}/tests
        run: ./originalbinary 2 3 >>origr

      - name: Check similarity
        working-directory: ${{github.workspace}}/tests
        run: cmp -s obsr origr
